### ISSUE TITLE
Support for Dart > 2.0?

### ISSUE THREAD

**Issue by bkbonner** [angel-dart/auth_google#2]
I was trying to walk through the chat app in the Angel docs.   updating it as I went for Dart 2.1 support.

  Angel version:  Angel 2.0 and Dart 2.1
  Steps to reproduce error:   walk through chat app w/ flultter
  Error message, stack trace and output (if available) 
`Because server depends on angel_auth_google >=1.0.0+1 which requires SDK version >=1.18.0 <2.0.0, version solving failed.`
  How urgently do you need the issue to be fixed?   when you get a chance

**Comment by thosakwe** [comment]
Hey, Brian, I should let you know that the chat article is over a year old, and is outdated, as in the time since, Dart 2 was released, and Angel began an upgrade to Angel 2 shortly thereafter. So just know that the instructions are likely to not work. I'll eventually put out a new article, and include a link to it, so that it's no longer confusing. Sorry about the inconvenience.

This package hasn't yet been updated, *but* it is on the tracker of items to resolve before the v2 release: https://github.com/angel-dart/angel/issues/78

It's not necessarily a difficult package to upgrade, but I think I will do the upgrade myself, because the changes required are not yet found in documentation.

I'm currently working on [`bullseye`](https://github.com/thosakwe/bullseye), but some time today I'll be working on Angel, and will make sure to publish an upgrade to this package.

**Comment by bkbonner** [comment]
Sounds good.   Sorry I missed issue 78.   Thanks for the quick response.

I currently do java dev and was looking for an alternative backend for
doing flutter work.      Having to have 3 stacks:   java (spring - server
side), javascript (angular - web client) and dart (ios/android) is kind of
a pain for smaller team development.   So I was looking to help ease that
pain.   I'm newer to flutter, but have been watching it keenly.  I want to
get some stuff developed w/ it.

**Comment by thosakwe** [comment]
Yes, Angel will be a good thing to work with if you want a single-language stack.

Also, after finishing updating `package:angel_auth_oauth2`, I've decided to archive this repo and point users there instead.

`auth_google` uses OAuth2 anyways, and relies on the Google+ API. Google+ will be closed some time this year, so this code would otherwise be bound to rot.

Of course, existing versions will always be there. Going forward, though, I can focus on maintaining just one package, and keeping that high-quality.

https://github.com/angel-dart/auth_oauth2
